spring:
  datasource:
    url: jdbc:h2:mem:overlayForStreams
    username: admin
    password: 123
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true